apiVersion: v1
kind: Secret
metadata:
  name: genmd-from-discord-bot
  namespace: genmd-from-discord-bot
type: Opaque
stringData:
  DISCORD_TOKEN: ""
  DISCORD_CLIENT_ID: ""
  DISCORD_GUILD_ID: ""
  ALLOWED_DISCORD_USER_IDS: ""
  GITHUB_TOKEN: ""
  GITHUB_OWNER: ""
  GITHUB_REPO: ""
